name: ci

on:
  push:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        php: ['7.4','8.0', '8.1', '8.2', '8.3']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer
          coverage: false
      - name: Install Dependencies
        run: composer update --prefer-dist --no-interaction
      - name: run tests
        run: composer test
      - name: run analyze
        run: composer analyze

  coverage:
    strategy:
      matrix:
        php: ['8.3']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer
          coverage: xdebug
      - name: Install Dependencies
        run: composer update --prefer-dist --no-interaction
      - name: run tests
        run: composer test
      - name: run analyze
        run: composer analyze
      - name: Make code coverage badge
        uses: timkrase/phpunit-coverage-badge@v1.2.1
        with:
          coverage_badge_path: output/coverage.svg
          push_badge: false

      - name: Git push to image-data branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./output
          publish_branch: image-data
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
